version: '3.8'

services:
  postgres:
    image: postgres:16.2-bullseye
    container_name: nested-set-postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nested-set-network

volumes:
  postgres-data:

networks:
  nested-set-network:
    driver: bridge
